# Generated by Django 6.0.4 on 2026-05-08 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='available_facing',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='available_sizes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='available_units',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='contact_info',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='location_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='number_of_units',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='pricing',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='total_project_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='type_of_approval',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='StorySeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by', to='prop.imagepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
